include/mastereq.hpp, include/oscillator.hpp, src/main.cpp, src/mastereq.cpp, src/oscillator.cpp
For efficiency, preallocate system matrices Ad,Bd,Ac,Bc in sparse-matrix
solver.
Remove explicit setup of NumberOperator and LoweringOperator. Set values
in the system matrix building blocks from paper-pen matrices.
The following commits have been squashed:
Print system dimensions in mastereq constructor.
Set up Bd from pen and paper.
Set control hamiltonian building blocks from pen and paper.
Adding decay and dephasing
Clean up. Don't add zero to mat.
Add Bc_vec.
Remove numberOperator and LoweringOperator.
Preallocate Hamiltonian matrices in sparse-mat solver.
Bugfix for preallocation.
Move check for lindblad options out of oscillator loop.
Create MPIAIJ mats even when on one processor.
Revert "Don't compute objectiveT. Don't write controls."
This reverts commit …
=> Preallocate sparse-mat Hamiltonians. Remove NumberOp.

include/optimproblem.hpp, include/util.hpp, results/gate_swap02/swap02.cfg, src/main.cpp, src/optimproblem.cpp, src/util.cpp
- The unitarity of intermediate conditions can be enforced by specifying the input `optim_unitarize_interm_ic=true`.
- This currently performs modified Gram-Schmidt operation on all processes, which needs parallelization in future.
=> Unitarity enforcement option for intermediate condition.

include/optimproblem.hpp, src/optimproblem.cpp, src/test_unitarize.cpp, src/util.cpp
- `OptimProblem::unitarize` and `OptimProblem::unitarize_grad` is now supported with the distributed optimization variable.
- In order to reduce the communication between processes, the classical GS orthonormalization is used. It has been observed that the condition number for classical GS is not so large, as intermediate states remain close to unitary state.
- `utils/compute_inner_product` now follows the conventional inner product between complex vectors.
- `OptimProblem` stores the original optimization variable into `x_b4unit` before unitarization, which is required for gradient calculation.
=> Unitarization with the distributed optimization variable

examples/pythoninterface/example_piecewise_constant_controls.py
This PR only contains a bug fix to remove a specific path to the quandary executable in one of the python examples
=> Removed a specific path to the quandary executable in a python example

examples/pythoninterface/optimize_then_perturb_controls.py
This PR adds a python example showing how the optimized control vector can be perturbed and the corresponding fidelity can be evaluated.
=> Perturburbing  the control vector from python

examples/pythoninterface/example_qft.py, examples/pythoninterface/optimize_then_perturb_controls.py, quandary.py
The PR includes changes to all the (pt, qt) lists that are returned from optimize() to allow perturbations of each segment of the control to easily be modified. The modified controls (pt2, qt2) can now be given as arguments to simulate(), where they are first downsampled and then used to construct a global pcof array that is used in the simulation.
=> Downsampling of (pt,qt) in simulate()

include/controlbasis.hpp, include/mastereq.hpp, include/optimproblem.hpp, include/optimtarget.hpp, include/oscillator.hpp, include/timestepper.hpp, src/CMakeLists.txt, src/config.cpp, src/controlbasis.cpp, src/gate.cpp, src/main.cpp, src/mastereq.cpp, src/optimproblem.cpp, src/optimtarget.cpp, src/oscillator.cpp, src/output.cpp, src/pythoninterface.cpp, src/timestepper.cpp, src/util.cpp
This PR re-enables compiler warnings and fixes them. The types of fixes are unused parameters/ variables, unsigned/signed comparisons, a deprecated Petsc function, and uninitialized variables. It may be easier to review by looking through the individual commits-- I tried to keep similar fixes all together.
=> Fix compiler warnings

.ci-scripts/build_and_test.sh, .github/workflows/test.yml, .gitlab/custom-jobs-and-variables.yml, .gitlab/jobs/lassen.yml, .gitlab/jobs/ruby.yml, CMakeLists.txt, regression_tests/regression_test.py, src/CMakeLists.txt
Some adjustments to the CI and build:
- Update the version of radiuss-spack-configs and make a few GitLab CI job fixes to make it build on LC machines
- Add linux github action next to mac-os one. This is useful for having a dockerized version of quandary as the linux spack package pushed to the buildcache can be run as a docker image.
- Add BLT not found error to CMake
- Remove unused linking to m, blas, lapack from CMake (was copied from Makefile but is not necessary as Petsc handles this)
- Fix parsing of mpiexec for tests (can be `flux;run` on certain machines so a bit of a hack to get that to work correctly)
Note: we still depend on my branch for radiuss-spack-configs and spack after this PR, will have to wait to update that. We need to wait til latest spack changes (to get the …
=> CI and build fixes

src/output.cpp
Expected energy and population need to be computed outside of the if-statement that check whether the file is open on this processor.
=> Bugfix for petsc-parallel output.

quandary.py
- Use `os.path.join` so paths separators are okay for windows 
- Use `\n` as the newline when opening file to avoid writing windows line endings
=> Minor windows fixes to quandary.py

.ci-scripts/build_and_test.sh, .pytest.ini, README.md, quandary.py, tests/performance/performance_test.py, tests/python/test_env_variable.py, tests/regression/regression_test.py
This PR:
- Adds environment variable `QUANDARY_BASE_DATADIR` to quandary.py to set a base output directory for both the config.cfg and output files. A user can still pass in a `datadir` and (if this is a relative path) this will be evaluated relative to the `QUANDARY_BASE_DATADIR` or if that is unset, then it will use the current working directory. When the environment variable is unset the behavior should be the same as it is currently. As the python code changes directories before executing quandary, it was not necessary to make changes to the C++ code for this.
- Adds tests for this to `tests/python`. These are also regression tests but need to be in their own folder, since the other regression tests rely on the folder structure for test cases.
- Add a `regression` and `performance` …
=> Add environment variable for output directory

quandary.py, tests/regression/regression_test.py
This PR:
- Fixes typo
- Fixes copy/paste bug in regression_test.py
- Fixes deprecation warning-- `numpy.ndarray` is recommended over `numpy.matix` which is deprecated. `ndarray` does not have Hermition, so use conjugate transpose instead.
=> Minor fixes

quandary.py
When evaluating the controls in the python interface, quandary's timestep size (dT) needs to be updated for the required sample rate of the pulses that are to be evaluated. Now the original dT is stored, the new dT for the sample rate overrides the member variable, then runs quandary, then resets to the original timestep size.
=> Bugfix evalControls: update timestepsize to match sampling rate.

tests/performance/convert_benchmark_format.py
Use median instead of mean on the benchmark dashboard as this is more resistant to outliers
=> Use median in performance tests

CMakeLists.txt, README.md
- don't always add `-O3` flag. Instead use CMAKE_BUILD_TYPE which will also add that flag if you set the type to release (default type) and can also set debug flags.
- Update radiuss-spack-configs version to include [changes](https://github.com/LLNL/radiuss-spack-configs/pull/129/files) I made to the Quandary spack package-- style fixes, add int64 variant that uses petsc int64 variant, use petsc debug variant when build_type=Debug
If you want to build in debug mode you can either use the spack spec `quandary build_type=Debug` which automatically uses petsc in debug mode, or with CMake you can do `cmake -DCMAKE_BUILD_TYPE=Debug ..`. With spack you can also choose petsc in 64 bit int mode using `quandary+int64`.
=> Make it easier to build with debug or int64 flags

include/gate.hpp, include/mastereq.hpp, include/optimtarget.hpp, include/oscillator.hpp, src/gate.cpp, src/mastereq.cpp, src/optimtarget.cpp, src/oscillator.cpp
Use const references for vectors/strings in function signatures to avoid unneccessary copies. These vectors/strings are likely very small so I don't think this will make any noticeable difference in performance. But stylistically I think it is nice because it makes it clear from the signature that you don't alter those.
=> Minor improvement: use const references for vectors

include/oscillator.hpp, src/main.cpp, src/oscillator.cpp
I came across this while making tests, and I think you did recently as well--
If you use a random control with a fixed random seed, on the LC machines you will get different results. This should be fixed by using the `mt19937` instead of `default_random_engine` (which uses different algorithms on different platforms) for random number generation.
=> Use cross platform reproducible random number generator

.github/workflows/test.yml
Fix a permission issue that may cause GitHub workflows to fail by only pushing to GHCR from this repo, not from forks
=> Fix a permission issue in GitHub workflow

CMakeLists.txt, include/version.hpp.in, pyproject.toml, src/CMakeLists.txt, src/main.cpp
- Add command `quandary --version` that prints out the version specified in CMakeLists.txt.
- Update the help that gets printed out when you do `./quandary`.
- Update the version to 4.2 (tag this commit as release)
- Update the version to 4.3-dev (this is the version that the code will have after the 4.2 release, since we are developing towards 4.3).
=> Add --version to binary and release 4.2

.github/workflows/build.yml, .github/workflows/doxygen.yml, .github/workflows/test.yml, .gitlab/jobs/tioga.yml, .spack_env/spack.yaml, CMakeLists.txt, README.md, docs/doxygen/Doxyfile.in, include/mastereq.hpp, include/output.hpp, src/mastereq.cpp, src/optimproblem.cpp, src/optimtarget.cpp, src/timestepper.cpp, src/util.cpp
This PR:
- Use spack variant +werror to build with flag `-Werror` (fails if there are compiler warnings) in a GitHub CI job. By default this flag is not used
- Adds build workflow that builds quandary with gcc and clang with +werror
- Updates doxygen workflow to run on PRs and fail if there are documentation warnings
- Fixes doxygen warnings
- Fixes compiler warnings
A few slightly unrelated changes:
-  Removes binary cache from spack.yaml which seems to slow down spack
- Updates radiuss-spack-configs module (needed to get the latest quandary spack package with werror variant)
- Fixes tioga CI for updated version of radiuss-spack-configs
=> Add warnings checks to GitHub workflows

.github/workflows/benchmark.yml
Improve GitHub benchmark workflow:
- separate PR check job from job that runs on main and pushes to the dashboard, which allows limiting the scope of the permissions on the PR job
- Update checkout action version and improve output from workflow
=> Improve GitHub benchmark workflow
